// functions/src/__tests__/purchaseAccountToken.test.ts
//
// The server half of the cross-language contract. The Dart half is
// test/core/purchases/purchase_account_token_test.dart and asserts the SAME
// vectors — that duplication is the entire point of this file.

import { NAMESPACE, purchaseTokenForUid } from '../purchaseAccountToken';

// ---------------------------------------------------------------------------
// The frozen vectors below were generated by an INDEPENDENT implementation
// (Python's stdlib `uuid.uuid5`), not by the code under test. That is
// deliberate: a vector produced by the implementation it checks proves only
// that the function is deterministic, which is not the property that matters.
//
// The property that matters is that TypeScript and Dart derive the SAME token
// from the same uid. The server recomputes uuidv5(NAMESPACE, request.auth.uid)
// and compares it to the token Apple carried on the transaction; if the two
// implementations disagree by one bit, every honest purchase is rejected and
// nothing in either codebase looks wrong. So the identical vectors are asserted
// on both sides of the wire.
// ---------------------------------------------------------------------------
const VECTORS: Record<string, string> = {
  'account-a': 'dab16d5c-6fc1-5338-a7c8-ab04e765232b',
  'account-b': '44fd022e-112f-5944-8cab-5df5513d70a7',
  '': 'c0ba420e-e4aa-5b20-a20d-f0b207701070',
};

describe('purchaseTokenForUid — the stamp Apple carries on the transaction', () => {
  test('matches the frozen cross-language vectors', () => {
    for (const [uid, expected] of Object.entries(VECTORS)) {
      expect(purchaseTokenForUid(uid)).toBe(expected);
    }
  });

  test('the namespace is byte-identical to the Dart constant', () => {
    // kPurchaseTokenNamespace in lib/core/purchases/purchase_account_token.dart.
    // Changing it re-derives every token and orphans the attribution on every
    // transaction Apple has already stamped.
    expect(NAMESPACE).toBe('6f9d3b2a-1c47-5e8a-9f30-2b7c5d41e8a6');
  });

  test('is a canonical lowercase v5 UUID, or Apple silently drops it', () => {
    // The Swift side does UUID(uuidString: token) and discards a value that
    // will not parse, with no error surfaced — so a malformed token means the
    // transaction simply arrives unstamped and looks like a legacy purchase.
    for (const uid of ['account-a', 'a', 'x'.repeat(200), '🧽']) {
      const token = purchaseTokenForUid(uid);
      expect(token).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    }
  });

  test('distinct uids derive distinct tokens', () => {
    const seen = new Set(
      ['a', 'b', 'c', 'account-a', 'account-b'].map(purchaseTokenForUid),
    );
    expect(seen.size).toBe(5);
  });
});
